<?php

define('CS_SC_BUTTON', 'cs_button');
define('CS_SC_TABS', 'cs_tabs');
define('CS_SC_TABSITEM', 'tab_item');
define('CS_SC_TOGGLE', 'cs_toggle');
define('CS_SC_PRICETABLE', 'cs_pricetable');
define('CS_SC_PRICETABLEITEM', 'pricing_item');
define('CS_SC_ACCORDION', 'cs_accordian');
define('CS_SC_ACCORDIONITEM', 'accordian_item');
define('CS_SC_CALLTOACTION', 'call_to_action');
define('CS_SC_COUNTERS', 'cs_counter');
define('CS_SC_PROGRESSBAR', 'cs_progressbars');
define('CS_SC_PROGRESSBARITEM', 'progressbar_item');
define('CS_SC_PIECHART', 'cs_piechart');
define('CS_SC_FAQ', 'cs_faq');
define('CS_SC_FAQITEM', 'faq_item');
define('CS_SC_TABLES', 'cs_table');
define('CS_SC_TABLE', 'table');
define('CS_SC_VIDEO', 'cs_video');
define('CS_SC_ABOUT', 'cs_about');
define('CS_SC_TABLEBODY', 'tbody');
define('CS_SC_TABLEHEAD', 'thead');
define('CS_SC_TABLEROW', 'tr');
define('CS_SC_TABLEHEADING', 'th');
define('CS_SC_TABLECOLUMN', 'td');
define('CS_SC_SERVICES', 'cs_services');
define('CS_SC_CLIENTS', 'cs_clients');
define('CS_SC_CLIENTSITEM', 'clients_item');
define('CS_SC_GALLERY', 'cs_gallery');
define('CS_SC_GALLERYITEM', 'gallery_item');
define('CS_SC_TWEETS', 'cs_tweets');
define('CS_SC_ICONBOX', 'cs_icon_box');
define('CS_SC_ICONBOXITEM', 'cs_icon_box_item');
define('CS_SC_INFOBOX', 'cs_infobox');
define('CS_SC_INFOBOXITEM', 'infobox_item');
define('CS_SC_ICONS', 'cs_icons');
define('CS_SC_TESTIMONIALS', 'cs_testimonials');
define('CS_SC_TESTIMONIALSITEM', 'testimonial_item');
define('CS_SC_IMAGE', 'cs_image');
define('CS_SC_SLIDER', 'cs_slider');
define('CS_SC_QUOTE', 'cs_slider');
define('CS_SC_QUICK_QUOTE', 'cs_quick_slider');
define('CS_SC_PROMOBOX', 'cs_promobox');
define('CS_SC_MAP', 'cs_map');
define('CS_SC_HEADING', 'cs_heading');
define('CS_SC_DIVIDER', 'cs_divider');
define('CS_SC_COLUMN', 'cs_column');
define('CS_SC_LIST', 'cs_list');
define('CS_SC_LISTITEM', 'list_item');
define('CS_SC_CONTACTUS', 'cs_contform');
define('CS_SC_SPACER', 'cs_spacer');
define('CS_SC_OFFERSLIDER', 'cs_offerslider');
define('CS_SC_OFFERITEM', 'offer_item');
define('CS_SC_FACILITIES', 'cs_facilities');
define('CS_SC_FACILITIESITEM', 'cs_facilities_item');
define('CS_SC_TEAM', 'cs_team');
define('CS_SC_SITEMAP', 'cs_sitemap');
define('CS_SC_MULTICOUNTERS', 'cs_multi_counters');
define('CS_SC_MULTICOUNTERSITEM', 'multi_counters_item');
define('CS_SC_MULTIPRICETABLE', 'cs_multi_price_table');
define('CS_SC_MULTIPRICETABLEITEM', 'multi_price_table_item');
define('CS_SC_EDITOR', 'cs_flex_editor');
define('CS_SC_PRICE_FEATURES', 'feature_item');
define('CS_SC_NEWSLETTER', 'jobcareer_newsletter');
define('CS_SC_MULTPLETEAM', 'jobcareer_multiple_team');
define('CS_SC_MULTPLETEAMITEM', 'cs_multiple_team_item');
//Translation
esc_html__('Call To Action', 'jobcareer');
esc_html__('Contact form', 'jobcareer');
esc_html__('Faq', 'jobcareer');
esc_html__('Flex Column', 'jobcareer');
esc_html__('Teams', 'jobcareer');
esc_html__('Mail chimp', 'jobcareer');
esc_html__('Price table', 'jobcareer');
esc_html__('Promo box', 'jobcareer');
esc_html__('Progress bars', 'jobcareer');